### ISSUE TITLE
Kodi veritabani

### ISSUE THREAD

**Issue by juk47ht** [hbiyik/service.subtitles.planetdp#12]
Merhaba. Turkce altyazi alanindaki acigi kapattigin icin tesekkurler. Calisan bir planetdp eklentisini uzun zamandir bekliyordum. Acaba bu ve turkcealtyazi eklentisi kodi veritabanina yuklenecek mi? Bahsettigim veritabi su: https://kodi.tv/addons/browse?keyword=&category=1171&author=&sort=title+ASC 

Kodi'ye add-on yukleme yontemi de soyle anlatilmis: http://kodi.wiki/view/Submitting_Add-ons

Tesekkurler

**Comment by hbiyik** [comment]
@juk47ht  düşünmüyorum, çünkü site güncellendiği zaman bu plugin patlayacak ve ben muhtemeln sürekli bunu maintain edemiyeceğim, sadece bana lazım olunca fix edeceğim :), maintain edecek birisi varsa forklayıp yükleyebilir.

**Comment by ahmetdereli** [comment]
Ben uzun zamandır hata alıyorum. Sizde eklenti çalışıyor mu? Üstteki yorumunuza istinaden soruyorum.
Turkcealtyazi.org'ta da benzer bir hata alıyorum. Hata logu aşağıdaki gibi.


``` Prolog
14:41:22.170 T:203057775856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'Nx27xtr',)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.planetdp/addon.py", line 23, in <module>
                                                service.planetdp("KODI / XBMC PlanetDP Subtitle Addon")
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.sublib/lib/sublib/model.py", line 108, in __init__
                                                method()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.sublib/lib/sublib/model.py", line 112, in _action_search
                                                self.search()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.planetdp/service.py", line 52, in search
                                                self.searchimdb()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.planetdp/service.py", line 258, in searchimdb
                                                return self.scrapesubs(page)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.planetdp/service.py", line 155, in scrapesubs
                                                iso = dptoiso[country]
                                            KeyError: (u'Nx27xtr',)
                                            -->End of Python script error report<--
14:41:22.188 T:202997937392   ERROR: GetDirectory - Error getting plugin://service.subtitles.planetdp/?action=search&languages=Turkish&preferredlanguage=Turkish
14:42:02.245 T:203057775856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.turkcealtyazi/addon.py", line 23, in <module>
                                                service.turkcealtyazi("KODI / XBMC Turkcealtyazi Subtitle Addon")
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.sublib/lib/sublib/model.py", line 108, in __init__
                                                method()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.sublib/lib/sublib/model.py", line 166, in _action_download
                                                self.download(*self._params["args"], **self._params["kwargs"])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.turkcealtyazi/service.py", line 242, in download
                                                fname = re.search('filename=(.*)', fname)
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-android-21/lib/python2.7/re.py", line 146, in search
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
14:42:02.273 T:202996901104   ERROR: GetDirectory - Error getting plugin://service.subtitles.turkcealtyazi/?action=%22download%22&languages=%22Turkish%22&args=%5B%22http%3A%2F%2Fwww.turkcealtyazi.org%2Fsub%2F711141%2Fshingeki-no-kyojin.html%22%5D&prefferedlanguage=%22Turkish%22&kwargs=%7B%7D
```

**Comment by hbiyik** [comment]
@juk47ht @ahmetdereli son commitle fixlendi,
